### ISSUE TITLE
Error on FullScreenHelper.ResetScreenCache when vertical panel location changed

### ISSUE THREAD

**Issue by rozputnii** [cairoshell/ManagedShell#100]
Object reference not set to an instance of an object.   

at ManagedShell.AppBar.FullScreenHelper.ResetScreenCache() in ManagedShell.AppBar\FullScreenHelper.cs:line 129
   at ManagedShell.AppBar.FullScreenHelper.NotifyScreensChanged() in ManagedShell.AppBar\FullScreenHelper.cs:line 134
   at ManagedShell.AppBar.AppBarWindow.SetScreenProperties(ScreenSetupReason reason) in ManagedShell.AppBar\AppBarWindow.cs:line 634
   at ManagedShell.AppBar.AppBarWindow.ProcessScreenChange(ScreenSetupReason reason) in ManagedShell.AppBar\AppBarWindow.cs:line 534
   at ManagedShell.AppBar.AppBarWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in ManagedShell.AppBar\AppBarWindow.cs:line 456
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by rozputnii** [comment]
Error reproduced only in .net 8

**Comment by dremin** [comment]
Fixed by #123.
